#!/usr/bin/python3.6
#coding: utf-8


class NodeContext():

    ''' Node context container

    The global context container for the Node class.
    Simply, we can just store the context info in the class' attributes.
    '''

    # pid of the worker
    pid = None

    # pid of the packet repeater worker
    pkt_rpter_pid = None

    # local IP address
    local_ip = None

    # the IDGenerator instance
    id_generator = None

    # The core instance
    core = None

    # The first instance of efferents that generated by the node
    main_efferent = None

    # the protocol wrapper instance generated by the node
    protocol_wrapper = None

    # The packet manager instance
    pkt_mgr = None
